AWSTemplateFormatVersion: '2010-09-09'

Description: This template will deploy an AWS Elastic Search Domain.

Parameters:
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base

Resources:
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-ES-Role'
      Description: 'This role will grant EC2 access to communiate with Systems Manager and CloudWatch'
      MaxSessionDuration: 3600 # in seconds
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
        - 'arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy'

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${AWS::StackName}-ES-Profile'
      Path: /
      Roles:
        - !Ref IamRole

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref LatestAmiId
      InstanceType: m4.large
      SecurityGroupIds:
        - !ImportValue DefaultSecurityGroup
      SubnetId: !ImportValue PublicSubnetA
      Tags:
        - Key: 'Name'
          Value: !Sub '${AWS::StackName}-ES-Instance'

  Domain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ElasticsearchClusterConfig:
        InstanceCount: 3
        # InstanceType: m4.medium.elasticsearch
        ZoneAwarenessEnabled: true
        ZoneAwarenessConfig:
          AvailabilityZoneCount: 3
      ElasticsearchVersion: 7.4
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 30
        VolumeType: gp2
      VPCOptions:
        SecurityGroupIds:
          - !ImportValue DefaultSecurityGroup
        SubnetIds:
          - !ImportValue PrivateSubnetA
          - !ImportValue PrivateSubnetB
          - !ImportValue PrivateSubnetC
