AWSTemplateFormatVersion: '2010-09-09'

Description: This template will deploy a sample AWS Open Search Domain.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Open Search Cluster Configuration
        Parameters:
          - SourceCidr
          - InstanceCount
          - InstanceType
          - EBSVolumeSize

Parameters:
  SourceCidr:
    Type: String
    Description: Provide a CIDR to allow source traffic
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Default: 172.31.0.0/16
  InstanceCount:
    Type: Number
    Description: Specify the number of instances for the Open Search Cluster
    Default: 3
    MinValue: 1
    MaxValue: 10
  InstanceType:
    Type: String
    Description: Select the EC2 Instance Size for members of the Open Search Cluster
    Default: t3.small.search
    AllowedValues:
      - t3.small.search
      - t3.medium.search
      - t3.large.search
      - t3.xlarge.search
      - m5.large.search
      - m5.xlarge.search
      - m5.2xlarge.search
      - m5.4xlarge.search
      - c5.large.search
      - c5.xlarge.search
      - c5.2xlarge.search
      - c5.4xlarge.search
      - c5.9xlarge.search
  EBSVolumeSize:
    Type: Number
    Description: Specify the size of the EBS volume for each instance
    Default: 30
    MinValue: 30

Resources:
  KmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub 'Encrypts data within our ${AWS::StackName} Open Search Cluster'
      EnableKeyRotation: true
      MultiRegion: false
      PendingWindowInDays: 7
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM Policies
            Effect: 'Allow'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:TagResource'
              - 'kms:UntagResource'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root'

  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    UpdatePolicy:
      EnableVersionUpgrade: true
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: !Sub 'arn:${AWS::Partition}:es:${AWS::Region}:${AWS::AccountId}:domain/*'
            Condition:
              IpAddress:
                aws:SourceIp: !Ref SourceCidr
      ClusterConfig:
        InstanceCount: !Ref InstanceCount
        InstanceType: !Ref InstanceType
        ZoneAwarenessEnabled: true
        ZoneAwarenessConfig:
          AvailabilityZoneCount: 3
      EncryptionAtRestOptions:
        Enabled: true
        KmsKeyId: !Ref KmsKey
      NodeToNodeEncryptionOptions:
        Enabled: true
      EBSOptions:
        EBSEnabled: true
        VolumeSize: !Ref EBSVolumeSize
        VolumeType: gp2
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-open-search'

Outputs:
  WebUrl:
    Value: !Sub 'https://${OpenSearchDomain.DomainEndpoint}/_dashboards'
    Description: The OpenSearch Dashboard URL
