AWSTemplateFormatVersion: '2010-09-09'

Description: Amazon Connect Contact Flow Primitive Product

Parameters:
  Namespace:
    Type: String
    Description: Provide a value to uniquely identify this deployment
    AllowedPattern: '[a-zA-Z0-9-]{3,8}'
    ConstraintDescription: Must be an alphanumeric value that can contain hyphens and is between 3 and 8 characters long
  ContactFlowContent:
    Type: String
    Description: Provide the content for the contact flow
  ContactFlowDescription:
    Type: String
    Description: Provide a friendly description of this contact flow
    AllowedPattern: '[a-zA-Z0-9 ]{3,100}'
    ConstraintDescription: Must be an alphanumeric value and is between 3 and 100 characters long
  ConnectInstanceArn:
    Type: String
    Description: Specify the full ARN of a Amazon Connect Instance to associate with
    AllowedPattern: 'arn:aws:connect:[a-z][a-z]-[a-z]+-[1-9]:[0-9]{12}:instance/*'
    ConstraintDescription: Must be a valid Amazon Connect Instance ARN
  ContactFlowName:
    Type: String
    Description: Provide a name for this contact flow
    AllowedPattern: '[a-zA-Z0-9]{3,16}'
    ConstraintDescription: Must be an alphanumeric value and is between 3 and 16 characters long
  ContactFlowState:
    Type: String
    Description: Select the desired state for the contact flow
    Default: ACTIVE
    AllowedValues:
      - ACTIVE
      - ARCHIVED
    ConstraintDescription: Must be a valid state of either ACTIVE or ARCHIVED
  ContactFlowType:
    Type: String
    Description: Select the type of contact flow to provision
    AllowedValues:
      - AGENT_HOLD
      - AGENT_TRANSFER
      - AGENT_WHISPER
      - CONTACT_FLOW
      - CUSTOMER_HOLD
      - CUSTOMER_QUEUE
      - CUSTOMER_WHISPER
      - OUTBOUND_WHISPER
      - QUEUE_TRANSFER
    ConstraintDescription: Must be a valid Contact Flow type

Resources:
  ContactFlow:
    Type: AWS::Connect::ContactFlow
    Properties:
      Content: !Ref ContactFlowContent
      Description: !Ref ContactFlowDescription
      InstanceArn: !Ref ConnectInstanceArn
      Name: !Sub '${Namespace}-${ContactFlowName}'
      State: !Ref ContactFlowState
      Type: !Ref ContactFlowType
      Tags:
        - Key: Name
          Value: !Sub '${Namespace}-${ContactFlowName}'

Outputs:
  ContactFlowName:
    Value: !Ref ContactFlow
    Description: The name of the contact flow
  ContactFlowArn:
    Value: !GetAtt ContactFlow.ContactFlowArn
    Description: The ARN of the contact flow
