AWSTemplateFormatVersion: '2010-09-09'

Description: Amazon Connect User Primitive Product

Parameters:
  Namespace:
    Type: String
    Description: Provide a value to uniquely identify this deployment
    AllowedPattern: '[a-zA-Z0-9-]{3,8}'
    ConstraintDescription: Must be an alphanumeric value that can contain hyphens and is between 3 and 8 characters long
  DirectoryUserId:
    Type: String
    Description: The identifier of the user account in the directory used for identity management
    Default: ''
  HierarchyGroupArn:
    Type: String
    Description: The full ARN of the user's hierarchy group
    Default: ''
  Email:
    Type: String
    Description: The email address of the user
    Default: ''
    AllowedPattern: ^$|^[\w!#$%&'*+/=?`{|}~^-]+(?:\.[\w!#$%&'*+/=?`{|}~^-]+)*@↵(?:[A-Z0-9-]+\.)+[A-Z]{2,6}$
    ConstraintDescription: Must be a valid email address
  FirstName:
    Type: String
    Description: The first name of the user
    Default: ''
    AllowedPattern: '^$|^[a-zA-Z]{1,100}$'
    ConstraintDescription: Must be an alphabet based value and is between 1 and 100 characters long
  LastName:
    Type: String
    Description: The last name of the user
    Default: ''
    AllowedPattern: '^$|^[a-zA-Z]{1,100}$'
    ConstraintDescription: Must be an alphabet based value and is between 1 and 100 characters long
  InstanceArn:
    Type: String
    Description: Specify the full ARN of a Amazon Connect Instance to associate with
    AllowedPattern: 'arn:aws:connect:[a-z][a-z]-[a-z]+-[1-9]:[0-9]{12}:instance/*'
    ConstraintDescription: Must be a valid Amazon Connect Instance ARN
  AfterContactWorkTimeLimit:
    Type: Number
    Description: The After Call Work (ACW) timeout setting, in seconds
    MinValue: 0
    MaxValue: 900
    ConstraintDescription: Must be a valid amount of seconds between 0 and 900
  AutoAccept:
    Type: String
    Description: Select true or false to enable auto accept features
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must select either true or false
  DeskPhoneNumber:
    Type: String
    Description: The phone number for the user's desk phone
    Default: ''
    AllowedPattern: ^$|^\\+[1-9]\\d{1,14}$
    ConstraintDescription: Must be a valid phone number in the E.164 format
  PhoneType:
    Type: String
    Description: The type of phone
    AllowedValues:
      - DESK_PHONE
      - SOFT_PHONE
    ConstraintDescription: Must be a valid phone type of either DESK_PHONE or SOFT_PHONE
  RoutingProfileArn:
    Type: String
    Description: Specify the full ARN of a Amazon Connect Routing Profile
    AllowedPattern: 'arn:aws:connect:[a-z][a-z]-[a-z]+-[1-9]:[0-9]{12}:instance/*'
    ConstraintDescription: Must be a valid Amazon Connect Routing Profile ARN
  SecurityProfileArns:
    Type: String
    Description: Specify the full ARN of a Amazon Connect Security Profile
    AllowedPattern: 'arn:aws:connect:[a-z][a-z]-[a-z]+-[1-9]:[0-9]{12}:instance/*'
    ConstraintDescription: Must be a valid Amazon Connect Security Profile ARN
  Username:
    Type: String
    Description: The user name assigned to the account
    AllowedPattern: '^[a-zA-Z0-9]{1,100}$'
    ConstraintDescription: Must be an alphanumeric value and is between 1 and 100 characters long

# Conditions:
#   EnableUserConfig: !Not [!And [!Equals [!Ref ContactFlowArn, ''], !Equals [!Ref UserArn, '']]]

Resources:
  User:
    Type: AWS::Connect::User
    Properties:
      DirectoryUserId: !Ref DirectoryUserId
      HierarchyGroupArn: !Ref HierarchyGroupArn
      IdentityInfo:
        Email: !Ref Email
        FirstName: !Ref FirstName
        LastName: !Ref LastName
      InstanceArn: !Ref InstanceArn
      PhoneConfig:
        AfterContactWorkTimeLimit: !Ref AfterContactWorkTimeLimit
        AutoAccept: !Ref AutoAccept
        DeskPhoneNumber: !Ref DeskPhoneNumber
        PhoneType: !Ref PhoneType
      RoutingProfileArn: !Ref RoutingProfileArn
      SecurityProfileArns:
        - !Ref SecurityProfileArns
      Username: !Ref Username
      Tags:
        - Key: Name
          Value: !Sub '${Namespace}-${Username}'

Outputs:
  UserJson:
    Value: !Ref User
    Description: The User JSON object
  UserArn:
    Value: !GetAtt User.UserArn
    Description: The User ARN
