name: CfnNag

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Execute cfn-nag
        uses: stelligent/cfn_nag@master
        with:
          input_path: example-stacks
          extra_args: --fail-on-warnings-o sarif
          output_path: cfn_nag.sarif

      - name: Upload to GitHub CodeQL
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cfn_nag.sarif
