name: CfnNag

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup cfn-nag
        uses: stelligent/cfn_nag@master
        with:
          input_path: example-stacks
          extra_args: -o sarif
          output_path: cfn_nag.sarif

      - name: Trigger cfn-nag
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cfn_nag.sarif

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
